version: '3.6'
services:
  server:
    container_name: api
    build:
      context: ./demo-container.server
      dockerfile: Dockerfile
    volumes: 
      - ./containerShared/prediction:/usr/src/app/src/static
      - ./containerShared/upload:/usr/scr/app/upload
    expose: 
      - 5000
    environment: 
      - FLASK_ENV=production
  client: 
    container_name: client
    build:
      context: ./demo-container.webclient
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
    # volumes: 
    #   - './deme-container/webclient:/usr/src/app'
    #   - '/usr/src/app/node_modules'
    # ports:
    #   - '3000:3000'
    environment: 
      - NODE_ENV=production
    expose: 
      - 80
    depends_on:
      - server

  nginx:
    container_name: nginx-server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:80
    depends_on:
      - server
      - client
